class StringResource():
    OBJECT_NAME_EN = {
        "person":"person",
        "bicycle":"bicycle",
        "car":"car",
        "motorbike":"motorbike",
        "aeroplane":"aeroplane",
        "bus":"bus",
        "train":"train",
        "truck":"truck",
        "boat":"boat",
        "traffic_light":"trafficlight",
        "fire_hydrant":"firehydrant",
        "stop_sign":"stopsign",
        "parking_meter":"parkingmeter",
        "bench":"bench",
        "bird":"bird",
        "cat":"cat",
        "dog":"dog",
        "horse":"horse",
        "sheep":"sheep",
        "cow":"cow",
        "elephant":"elephant",
        "bear":"bear",
        "zebra":"zebra",
        "giraffe":"giraffe",
        "backpack":"backpack",
        "umbrella":"umbrella",
        "handbag":"handbag",
        "tie":"tie",
        "suitcase":"suitcase",
        "frisbee":"frisbee",
        "skis":"skis",
        "snowboard":"snowboard",
        "sports_ball":"sportsball",
        "kite":"kite",
        "baseball_bat":"baseballbat",
        "baseball_glove":"baseballglove",
        "skateboard":"skateboard",
        "surfboard":"surfboard",
        "tennis_racket":"tennisracket",
        "bottle":"bottle",
        "wine_glass":"wineglass",
        "cup":"cup",
        "fork":"fork",
        "knife":"knife",
        "spoon":"spoon",
        "bowl":"bowl",
        "banana":"banana",
        "apple":"apple",
        "sandwich":"sandwich",
        "orange":"orange",
        "broccoli":"broccoli",
        "carrot":"carrot",
        "hot_dog":"hotdog",
        "pizza":"pizza",
        "donut":"donut",
        "cake":"cake",
        "chair":"chair",
        "sofa":"sofa",
        "pottedplant":"pottedplant",
        "bed":"bed",
        "diningtable":"diningtable",
        "toilet":"toilet",
        "tvmonitor":"tvmonitor",
        "laptop":"laptop",
        "mouse":"mouse",
        "remote":"remote",
        "keyboard":"keyboard",
        "cell_phone":"cellphone",
        "microwave":"microwave",
        "oven":"oven",
        "toaster":"toaster",
        "sink":"sink",
        "refrigerator":"refrigerator",
        "book":"book",
        "clock":"clock",
        "vase":"vase",
        "scissors":"scissors",
        "teddy_bear":"teddybear",
        "hair_drier":"hairdrier",
        "toothbrush":"toothbrush",
        "glass": "glass",
    }

    OBJECT_NAME_JA = {
        "person":"人",
        "bicycle":"自転車",
        "car":"車",
        "motorbike":"バイク",
        "aeroplane":"飛行機",
        "bus":"バス",
        "train":"列車",
        "truck":"トラック",
        "boat":"ボート",
        "traffic_light":"信号機",
        "fire_hydrant":"消火栓",
        "stop_sign":"一時停止標識",
        "parking_meter":"パーキングメーター",
        "bench":"ベンチ",
        "bird":"鳥",
        "cat":"ネコ",
        "dog":"犬",
        "horse":"うま",
        "sheep":"羊",
        "cow":"牛",
        "elephant":"象",
        "bear":"くま",
        "zebra":"シマウマ",
        "giraffe":"キリン",
        "backpack":"バックパック",
        "umbrella":"傘",
        "handbag":"ハンドバッグ",
        "tie":"ネクタイ",
        "suitcase":"スーツケース",
        "frisbee":"フリスビー",
        "skis":"スキー板",
        "snowboard":"スノーボード",
        "sports_ball":"スポーツボール",
        "kite":"カイト",
        "baseball_bat":"野球用バット",
        "baseball_glove":"野球グローブ",
        "skateboard":"スケートボード",
        "surfboard":"サーフボード",
        "tennis_racket":"テニスラケット",
        "bottle":"ボトル",
        "wine_glass":"ワイングラス",
        "cup":"カップ",
        "fork":"フォーク",
        "knife":"ナイフ",
        "spoon":"スプーン",
        "bowl":"ボウル",
        "banana":"バナナ",
        "apple":"林檎",
        "sandwich":"サンドイッチ",
        "orange":"オレンジ",
        "broccoli":"ブロッコリ",
        "carrot":"にんじん",
        "hot_dog":"ホットドッグ",
        "pizza":"ピザ",
        "donut":"ドーナツ",
        "cake":"ケーキ",
        "chair":"椅子",
        "sofa":"ソファー",
        "pottedplant":"鉢植え",
        "bed":"ベッド",
        "diningtable":"ダイニングテーブル",
        "toilet":"トイレ",
        "tvmonitor":"モニター",
        "laptop":"ラップトップ",
        "mouse":"マウス",
        "remote":"リモート",
        "keyboard":"キーボード",
        "cell_phone":"携帯電話",
        "microwave":"電子レンジ",
        "oven":"オーブン",
        "toaster":"トースター",
        "sink":"シンク",
        "refrigerator":"冷蔵庫",
        "book":"本",
        "clock":"時計",
        "vase":"花瓶",
        "scissors":"はさみ",
        "teddy_bear":"テディベア",
        "hair_drier":"ヘアドライヤー",
        "toothbrush":"歯ブラシ",
        "glass":"グラス"
    }

    MSG_CANNOT_FOUND_OBJECT = "画像にオブジェクトが見つかりません。"

    TEXT_CORLOR = [
        (76, 60, 231, 0),
        (84, 0 , 211, 0),
        (112, 99, 236, 0),
        (46, 204, 113, 0),
        (67, 53 , 203, 0),
        (13, 74, 238, 0),
        (238, 224, 13, 0),
    ]

    
